name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
      name: Build and Test
      timeout-minutes: 60
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
          with: 
            fetch-depth: 2
        - uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'
            cache: 'yarn'
 
        - name: Install dependencies 🧳
          run: yarn install --frozen-lockfile

        - name: Install Playwright Browsers 🕹️
          run: npx playwright install --with-deps

        - name: Check Lint 💅🏻
          run: yarn lint
 
        - name: Run Build 🔨
          run: yarn build
 
        - name: Run Tests 🧪
          run: yarn e2e:test
        
        - name: Danger Checks ☢️
          run: yarn danger ci
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
