name = "tail"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "tail.lenstube.xyz", custom_domain = true }
]
keep_vars = true

[env.production.vars]
LOGTAIL_API_KEY = ""
